### PR TITLE
Fix transform error

### PR DESCRIPTION
**Pull request by luchaoqi**
Getting error `TypeError: img should be PIL Image. Got <class 'torch.Tensor'>` when `Resize` on `torch.Tensor` instead of `PIL.Images`

### CODE REVIEW

**Comment by oneThousand1000** [comment]
For torchvision 0.8.2, the image fed into transforms.Resize can be a PIL Image or a torch Tensor, in which case it is expected to have [..., H, W] shape, where ... means an arbitrary number of leading dimensions. 
Could you please tell me the vision of your torchvision? As I can not reproduce bug the bug you posted.

**Comment by oneThousand1000** [comment]
Here is the versions of the required packages I used:  https://github.com/oneThousand1000/EG3D-projector/issues/8#issuecomment-1290332237

**Comment by luchaoqi** [comment]
> For torchvision 0.12.0, the image fed into transforms.Resize can be a PIL Image or a torch Tensor, in which case it is expected to have [..., H, W] shape, where ... means an arbitrary number of leading dimensions. Could you please tell me the vision of your torchvision? As I can not reproduce bug the bug you posted.

I'm using 0.2.2, I believe it's a bit outdated tho.

**Comment by oneThousand1000** [comment]
> > For torchvision 0.12.0, the image fed into transforms.Resize can be a PIL Image or a torch Tensor, in which case it is expected to have [..., H, W] shape, where ... means an arbitrary number of leading dimensions. Could you please tell me the vision of your torchvision? As I can not reproduce bug the bug you posted.
> 
> I'm using 0.2.2, I believe it's a bit outdated tho.

I will update the readme.

**Pull request closed without merging**
